<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net462</TargetFramework>
        <LangVersion Condition="'$(TargetFramework)'=='net462'">latest</LangVersion>
        <UseWPF>true</UseWPF>
        <RootNamespace>MapControl.UiTools</RootNamespace>
        <AssemblyTitle>XAML Map Control UI Tools Library for WPF</AssemblyTitle>
        <DefineConstants>WPF</DefineConstants>
        <Product>XAML Map Control</Product>
        <Version>17.1.0</Version>
        <Authors>Clemens Fischer</Authors>
        <Copyright>Copyright © Clemens Fischer</Copyright>
        <SignAssembly>true</SignAssembly>
        <AssemblyOriginatorKeyFile>..\MapControl.snk</AssemblyOriginatorKeyFile>
        <DelaySign>false</DelaySign>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\MapControl.snk" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="..\Shared\*.cs" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="XAML.MapControl.WPF" Version="17.1.0" />
    </ItemGroup>

</Project>
