// *****************************************************************************
// * This is an automatically generated header file for UI Element definition  *
// * resource symbols and values. Please do not modify manually.               *
// *****************************************************************************

#pragma once

#define cmdQAT 2 
#define cmdApplication 3 
#define CmdTabChart 4 
#define CmdTabChart_LabelTitle_RESID 60001
#define cmdTabView 5 
#define cmdTabView_LabelTitle_RESID 60002
#define cmdGroupChartPower1 6 
#define cmdGroupChartPower1_LabelTitle_RESID 60003
#define cmdGroupChartPower1_TooltipTitle_RESID 60004
#define cmdGroupChartPower1_TooltipDescription_RESID 60005
#define cmdGroupChartSpeed 7 
#define cmdGroupChartSpeed_LabelTitle_RESID 60006
#define cmdGroupChartSpeed_TooltipTitle_RESID 60007
#define cmdGroupChartSpeed_TooltipDescription_RESID 60008
#define cmdGroupChartClimbing 8 
#define cmdGroupChartClimbing_LabelTitle_RESID 60009
#define cmdGroupChartClimbing_TooltipTitle_RESID 60010
#define cmdGroupChartClimbing_TooltipDescription_RESID 60011
#define cmdButtonPower 9 
#define cmdButtonPower_LabelTitle_RESID 60012
#define cmdButtonPower_TooltipTitle_RESID 60013
#define cmdButtonPower_TooltipDescription_RESID 60014
#define cmdButtonLRBalance 10 
#define cmdButtonLRBalance_LabelTitle_RESID 60015
#define cmdButtonLRBalance_TooltipTitle_RESID 60016
#define cmdButtonLRBalance_TooltipDescription_RESID 60017
#define cmdButtonLSmoothness 11 
#define cmdButtonLSmoothness_LabelTitle_RESID 60018
#define cmdButtonLSmoothness_TooltipTitle_RESID 60019
#define cmdButtonLSmoothness_TooltipDescription_RESID 60020
#define cmdButtonRSmoothness 12 
#define cmdButtonRSmoothness_LabelTitle_RESID 60021
#define cmdButtonRSmoothness_TooltipTitle_RESID 60022
#define cmdButtonRSmoothness_TooltipDescription_RESID 60023
#define cmdButtonLTorqueEff 13 
#define cmdButtonLTorqueEff_LabelTitle_RESID 60024
#define cmdButtonLTorqueEff_TooltipTitle_RESID 60025
#define cmdButtonLTorqueEff_TooltipDescription_RESID 60026
#define cmdButtonRTorqueEff 14 
#define cmdButtonRTorqueEff_LabelTitle_RESID 60027
#define cmdButtonRTorqueEff_TooltipTitle_RESID 60028
#define cmdButtonRTorqueEff_TooltipDescription_RESID 60029
#define cmdButtonOpen 15 
#define cmdButtonOpen_LabelTitle_RESID 60030
#define cmdButtonOpen_TooltipTitle_RESID 60031
#define cmdButtonOpen_TooltipDescription_RESID 60032
#define cmdButtonOpen_SmallImages_96__RESID 60033
#define cmdButtonOpen_SmallImages_120__RESID 60034
#define cmdButtonOpen_SmallImages_144__RESID 60035
#define cmdButtonOpen_SmallImages_192__RESID 60036
#define cmdButtonOpen_LargeImages_96__RESID 60037
#define cmdButtonOpen_LargeImages_120__RESID 60038
#define cmdButtonOpen_LargeImages_144__RESID 60039
#define cmdButtonOpen_LargeImages_192__RESID 60040
#define cmdButtonSaveGpx 16 
#define cmdButtonSaveGpx_LabelTitle_RESID 60041
#define cmdButtonSaveGpx_TooltipTitle_RESID 60042
#define cmdButtonSaveGpx_TooltipDescription_RESID 60043
#define cmdButtonExit 17 
#define cmdButtonExit_LabelTitle_RESID 60044
#define cmdButtonExit_SmallImages_96__RESID 60045
#define cmdButtonExit_SmallImages_120__RESID 60046
#define cmdButtonExit_SmallImages_144__RESID 60047
#define cmdButtonExit_SmallImages_192__RESID 60048
#define cmdButtonExit_LargeImages_RESID 60049
#define cmdButtonHelp 18 
#define cmdButtonHeartRate 19 
#define cmdButtonHeartRate_LabelTitle_RESID 60050
#define cmdButtonHeartRate_TooltipTitle_RESID 60051
#define cmdButtonHeartRate_TooltipDescription_RESID 60052
#define cmdButtonHeartRate_SmallImages_96__RESID 60053
#define cmdButtonHeartRate_SmallImages_120__RESID 60054
#define cmdButtonHeartRate_SmallImages_144__RESID 60055
#define cmdButtonHeartRate_SmallImages_192__RESID 60056
#define cmdButtonAltitude 20 
#define cmdButtonAltitude_LabelTitle_RESID 60057
#define cmdButtonGrade 21 
#define cmdButtonGrade_LabelTitle_RESID 60058
#define cmdButtonSpeed 22 
#define cmdButtonSpeed_LabelTitle_RESID 60059
#define cmdButtonSpeed_TooltipTitle_RESID 60060
#define cmdButtonSpeed_TooltipDescription_RESID 60061
#define cmdButtonCadence 23 
#define cmdButtonCadence_LabelTitle_RESID 60062
#define cmdButtonCadence_TooltipTitle_RESID 60063
#define cmdButtonCadence_TooltipDescription_RESID 60064
#define cmdButtonTemperature 24 
#define cmdButtonTemperature_LabelTitle_RESID 60065
#define cmdButtonTemperature_TooltipTitle_RESID 60066
#define cmdButtonTemperature_TooltipDescription_RESID 60067
#define cmdGroupChartEffectiveness1 25 
#define cmdGroupChartEffectiveness1_LabelTitle_RESID 60068
#define cmdGroupChartEffectiveness1_TooltipDescription_RESID 60069
#define cmdGroupChartSmoothness1 26 
#define cmdGroupChartSmoothness1_LabelTitle_RESID 60070
#define cmdGroupChartSmoothness1_TooltipDescription_RESID 60071
#define cmdGroupChartExtras 27 
#define cmdGroupChartExtras_LabelTitle_RESID 60072
#define cmdGroupChartSelect 28 
#define cmdGroupChartSelect_LabelTitle_RESID 60073
#define cmdGroupChartSelect_TooltipDescription_RESID 60074
#define cmdComboSelect 29 
#define cmdComboSelect_LabelTitle_RESID 60075
#define cmdComboSelect_TooltipTitle_RESID 60076
#define cmdComboSelect_TooltipDescription_RESID 60077
#define cmdComboSelect_SmallImages_RESID 60078
#define cmdComboSelect_SmallImages_120__RESID 60079
#define cmdComboSelect_SmallImages_144__RESID 60080
#define cmdComboSelect_SmallImages_192__RESID 60081
#define cmdComboPower 30 
#define cmdComboPower_TooltipTitle_RESID 60082
#define cmdComboPower_TooltipDescription_RESID 60083
#define cmdComboLRBalance 31 
#define cmdComboLRBalance_TooltipTitle_RESID 60084
#define cmdComboLRBalance_TooltipDescription_RESID 60085
#define cmdComboLSmoothness 32 
#define cmdComboLSmoothness_TooltipTitle_RESID 60086
#define cmdComboLSmoothness_TooltipDescription_RESID 60087
#define cmdComboRSmoothness 33 
#define cmdComboRSmoothness_TooltipTitle_RESID 60088
#define cmdComboRSmoothness_TooltipDescription_RESID 60089
#define cmdComboLTorque 34 
#define cmdComboLTorque_TooltipTitle_RESID 60090
#define cmdComboLTorque_TooltipDescription_RESID 60091
#define cmdComboRTorque 35 
#define cmdComboRTorque_TooltipTitle_RESID 60092
#define cmdComboRTorque_TooltipDescription_RESID 60093
#define cmdGroupTotals 37 
#define cmdGroupTotals_LabelTitle_RESID 60094
#define cmdGroupZones 38 
#define cmdGroupZones_LabelTitle_RESID 60095
#define cmdGroupZones_TooltipTitle_RESID 60096
#define cmdGroupZones_TooltipDescription_RESID 60097
#define cmdGroupExtras 39 
#define cmdGroupExtras_LabelTitle_RESID 60098
#define cmdGroupChartPower 40 
#define cmdGroupChartPower_LabelTitle_RESID 60099
#define cmdGroupChartPower_TooltipTitle_RESID 60100
#define cmdGroupChartPower_TooltipDescription_RESID 60101
#define cmdGroupChartEffectiveness 41 
#define cmdGroupChartEffectiveness_LabelTitle_RESID 60102
#define cmdGroupChartEffectiveness_TooltipDescription_RESID 60103
#define cmdGroupChartSmoothness 42 
#define cmdGroupChartSmoothness_LabelTitle_RESID 60104
#define cmdGroupChartSmoothness_TooltipDescription_RESID 60105
#define cmdButtonSession 43 
#define cmdButtonSession_LabelTitle_RESID 60106
#define cmdButtonSession_TooltipTitle_RESID 60107
#define cmdButtonSession_TooltipDescription_RESID 60108
#define cmdButtonSession_SmallImages_96__RESID 60109
#define cmdButtonSession_SmallImages_120__RESID 60110
#define cmdButtonSession_SmallImages_144__RESID 60111
#define cmdButtonSession_SmallImages_192__RESID 60112
#define cmdButtonSession_LargeImages_96__RESID 60113
#define cmdButtonSession_LargeImages_120__RESID 60114
#define cmdButtonSession_LargeImages_144__RESID 60115
#define cmdButtonSession_LargeImages_192__RESID 60116
#define cmdButtonLaps 44 
#define cmdButtonLaps_LabelTitle_RESID 60117
#define cmdButtonLaps_TooltipTitle_RESID 60118
#define cmdButtonLaps_TooltipDescription_RESID 60119
#define cmdButtonLaps_SmallImages_96__RESID 60120
#define cmdButtonLaps_SmallImages_120__RESID 60121
#define cmdButtonLaps_SmallImages_144__RESID 60122
#define cmdButtonLaps_SmallImages_192__RESID 60123
#define cmdButtonHeartRateZones 45 
#define cmdButtonHeartRateZones_LabelTitle_RESID 60124
#define cmdButtonHeartRateZones_TooltipTitle_RESID 60125
#define cmdButtonHeartRateZones_TooltipDescription_RESID 60126
#define cmdButtonHeartRateZones_SmallImages_RESID 60127
#define cmdButtonPowerZones 46 
#define cmdButtonPowerZones_LabelTitle_RESID 60128
#define cmdButtonPowerZones_TooltipTitle_RESID 60129
#define cmdButtonPowerZones_TooltipDescription_RESID 60130
#define cmdButtonPowerZones_SmallImages_RESID 60131
#define cmdToggleSmooth 47 
#define cmdToggleSmooth_LabelTitle_RESID 60132
#define cmdToggleSmooth_TooltipTitle_RESID 60133
#define cmdToggleSmooth_TooltipDescription_RESID 60134
#define cmdToggleSmooth_SmallImages_RESID 60135
#define cmdToggleSmooth_SmallImages_120__RESID 60136
#define cmdToggleSmooth_SmallImages_144__RESID 60137
#define cmdToggleSmooth_SmallImages_192__RESID 60138
#define cmdButtonAbout 48 
#define cmdButtonAbout_LabelTitle_RESID 60139
#define cmdButtonAbout_SmallImages_96__RESID 60140
#define cmdButtonAbout_SmallImages_120__RESID 60141
#define cmdButtonAbout_SmallImages_144__RESID 60142
#define cmdButtonAbout_SmallImages_192__RESID 60143
#define cmdButtonAbout_LargeImages_96__RESID 60144
#define cmdButtonAbout_LargeImages_120__RESID 60145
#define cmdButtonAbout_LargeImages_144__RESID 60146
#define cmdButtonAbout_LargeImages_192__RESID 60147
#define cmdButtonMyExtras 49 
#define cmdButtonMyExtras_LabelTitle_RESID 60148
#define cmdButtonMyExtras_TooltipTitle_RESID 60149
#define cmdButtonMyExtras_TooltipDescription_RESID 60150
#define cmdGroupIntern 50 
#define cmdGroupIntern_LabelTitle_RESID 60151
#define cmdButtonActivity 52 
#define cmdButtonActivity_LabelTitle_RESID 60152
#define cmdButtonActivity_TooltipTitle_RESID 60153
#define cmdButtonDeveloperDataId 53 
#define cmdButtonDeveloperDataId_LabelTitle_RESID 60154
#define cmdButtonDeveloperDataId_TooltipTitle_RESID 60155
#define cmdButtonDeviceInfo 54 
#define cmdButtonDeviceInfo_LabelTitle_RESID 60156
#define cmdButtonDeviceInfo_TooltipTitle_RESID 60157
#define cmdButtonEvent 55 
#define cmdButtonEvent_LabelTitle_RESID 60158
#define cmdButtonEvent_TooltipTitle_RESID 60159
#define cmdButtonFieldDescription 56 
#define cmdButtonFieldDescription_LabelTitle_RESID 60160
#define cmdButtonFieldDescription_TooltipTitle_RESID 60161
#define cmdButtonFileId 57 
#define cmdButtonFileId_LabelTitle_RESID 60162
#define cmdButtonFileId_TooltipTitle_RESID 60163
#define cmdButtonSport 58 
#define cmdButtonSport_LabelTitle_RESID 60164
#define cmdButtonSport_TooltipTitle_RESID 60165
#define cmdButtonWorkout 59 
#define cmdButtonWorkout_LabelTitle_RESID 60166
#define cmdButtonWorkout_TooltipTitle_RESID 60167
#define cmdButtonWahooFF00 60 
#define cmdButtonWahooFF00_LabelTitle_RESID 60168
#define cmdButtonWahooFF00_TooltipTitle_RESID 60169
#define cmdButtonWahooFF01 61 
#define cmdButtonWahooFF01_LabelTitle_RESID 60170
#define cmdButtonWahooFF01_TooltipTitle_RESID 60171
#define cmdButtonSetSettings 64 
#define cmdButtonSetSettings_LabelTitle_RESID 60172
#define cmdButtonSetSettings_TooltipTitle_RESID 60173
#define cmdButtonSetSettings_TooltipDescription_RESID 60174
#define cmdButtonMap 62 
#define cmdButtonMap_LabelTitle_RESID 60175
#define cmdButtonMap_TooltipTitle_RESID 60176
#define cmdButtonMap_TooltipDescription_RESID 60177
#define cmdGroupMaps 63 
#define cmdGroupMaps_LabelTitle_RESID 60178
